# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AR/VR Game
email: yrsun@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  Hi this is Yiru Sun, or you can call me Yuri. I am senior year computer engineering student at University of California, Davis. 
  This blog is all about my senior design, AR/VR Game. As team leader, I am mainly responsible for Game interface, script programming
  and other management tasks. Please feel free to send me email and please dont hesitate to ask my any question.
baseurl: "/jekyll-simple" # the subpath of your site, e.g. /blog
url: "yrsun.github.io" # the base hostname & protocol for your site
twitter_username: yrsun 
github_username:  yrsun 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
